### ISSUE TITLE
No devices from the API

### ISSUE THREAD

**Issue by dny238** [jfarmer08/ha-sengledapi#1]
I've installed everything with HAC. Newbie here...

In my Core log I find... 
2020-06-09 16:49:59 INFO (SyncWorker_6) [homeassistant.loader] Loaded sengledapi from custom_components.sengledapi

I added the following under default_config: in my configuration.yaml

```
default_config:

logger:
  default: warning
  logs:
    custom_components.sengledapi: debug
```

My home assistant install is on http://192.168.86.98/
A wifi bulb is at 192.168.86.29
Sengled hub is 192.168.86.28

Where can I find the debug log? 
Is there an action I need to take to initiate the search for the devices or will it automatically try to find them?
