### ISSUE TITLE
Error when validating configuration

### ISSUE THREAD

**Issue by dschmidtadv** [jfarmer08/ha-sengledapi#85]
**Describe the bug**
After adding configuration to configuration.yml I am receiving an error when validating configration in developer tools before restarting HA
**To Reproduce**
1. add configuration to /config/configuration.yaml
2. Click on 'Developer Tools'
3. Click on "Check Configuration"
4. Error Message: Integration error: sengledapi - Integration 'sengledapi' not found.

**System configuration**
System: 
HA Version: 
SengledApi Version:  

**configuration.yaml**

```yaml

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sengledapi:
  username: dietric@gmail.com
  password: xxxxxxxx
  country: us
  wifi: true
```

**home-assistant.log**
<!--
Ensure that your logger is set up by adding this to your configuration.yaml
logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug

For additional information see the readme: https://github.com/jfarmer08/ha-sengledapi#reporting-an-issue
```
<PUT YOUR LOG HERE>
```
